name: Things

env:
  REF_NAME: ${{ github.ref_name }}

on:
  push:
    branches: [master, main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate Tag
      run: bin/gentag
